### PR TITLE
jsdom-react: simulate click events in the correct order

### PR DESCRIPTION
**Pull request by zemlanin**
see also:
- https://jsbin.com/larubagiwu/1/edit?html,js,console,output
- https://github.com/wix-incubator/unidriver/pull/86#issuecomment-516809527

---

to install adapter from the branch as a dependency for package `A`:
- clone the repo
- check out the branch
- run `npm run build && npm test && cd adapters/jsdom-react && npm pack`, notice newly created `.tgz` archive
- `cd` to your package `A` and run `npm i [path-to-the-tgz]`

### CODE REVIEW

**Comment by GabiGrin** [comment]
@zemlanin can we add a test that verifies the right call order? I remember you've added one

**Comment by zemlanin** [comment]
@GabiGrin done https://github.com/wix-incubator/unidriver/pull/88/commits/b075fd4ece2becaf31d24ef4d7bab90fbcff72b4

**Comment by mosheKerbel** [comment]
@GabiGrin @borisd9  
could you publish a new version to reflect the new changes?
thanks

**Comment by GabiGrin** [comment]
@mosheKerbel  released

**Pull request merged**
