### PR TITLE
protractor: Fix package.json main and typings

### PR DESCRIPTION
**Pull request by hepiyellow**
Because I previously added `protractor.conf` to the `tsconfig` ([here](https://github.com/wix-incubator/unidriver/blob/cf59c1a531c97374818a8d61825facc1bf10ec9b/adapters/protractor/tsconfig.json#L9)), then now the `dist` folder has ` src` folder in it.

- So `@unidriver/protractor@1.1.4` is broken
- After merging this fix, we should release `1.1.5`

Thanks.

### CODE REVIEW

**Comment by GabiGrin** [comment]
@hepiyellow I prefer to refrain of `/dist/src
Instead, it's easier to just turn protractor.ts into .js 
PS: I think that .ts for config files is a bit of an overkill anyhow

**Comment by GabiGrin** [comment]
OK I take that back - it has imports and uses stuff from test suite
I moved it to `src` instead

**Comment by hepiyellow** [comment]
Yeah, the protractor.conf and the spec share the test server port. 
If you are strongly against dist/src,
I can put protractor.conf under src (as a quick fix)
Or I can give another try, to start the server from the spec. I couldn’t do it the first time I tried.

**Comment by hepiyellow** [comment]
@gabigrin so?

**Comment by hepiyellow** [comment]
@GabiGrin @borisd9 Can you merge and publish?

**Comment by hepiyellow** [comment]
@GabiGrin Build is green

**Pull request merged**
