### PR TITLE
Add mouse.leave function

### PR DESCRIPTION
**Pull request by EgoziE**

### CODE REVIEW

**Comment by GabiGrin** [comment]
LGTM
Bummer that the mouse simulation in pptr / playwright is done using dom events injecting and not via a "true" mouse simulation (as in `Page.mouse.move()`) but I see previous events were implemented like that so guess it's ok

**Comment by GabiGrin** [comment]
@Dor256 any ideas why the PW fails

**Comment by GabiGrin** [comment]
@EgoziE  just saw the failing test :sigh:
pinging @Dor256 who wrote the adapter - any pointers for @EgoziE  to save us some time?

**Comment by Dor256** [comment]
> @EgoziE just saw the failing test :sigh:
> pinging @Dor256 who wrote the adapter - any pointers for @EgoziE to save us some time?

Hmm not sure actually...
I see that in the `puppeteer` driver you used a `mouseout` event while in `playwright` you used a `mouseleave` event.
Could this be affecting this?

**Comment by EgoziE** [comment]
Unfortunately, for puppeteer only `mouseout` actually triggered the `mouseleave` event.
I found it by accident

**Comment by EgoziE** [comment]
@Dor256 What are you suggesting?
(and how can I run `playwright` tests locally? I didn't succeed)

**Comment by Dor256** [comment]
> @Dor256 What are you suggesting?
> (and how can I run `playwright` tests locally? I didn't succeed)

Did you try using`mouseout` on `playwright` as well?
Regarding running it locally, `npm test` should work unless something changed...

**Pull request merged**
