### PR TITLE
enterValue - don't enter value when input is readOnly

### PR DESCRIPTION
**Pull request by bamai**
Following this thread:
https://wix.slack.com/archives/CM7M5R10W/p1617785086003100

### CODE REVIEW

**Review by GabiGrin — APPROVED** [review]
Looks great @bamai, thanks!
Will release this soon

**Comment by sivanharel** [comment]
@GabiGrin -
Thanks for the quick response!
If I am not wrong we might need to change it from 'readOnly' to 'readonly' since the HTML attribute that is added is with 'o' and not 'O'.
https://www.w3schools.com/tags/att_input_readonly.asp

I could open a new pr with this fix, so maybe we could wait with the release?

**Comment by GabiGrin** [comment]
@sivanharel  sure

**Comment by GabiGrin** [comment]
It's ok, we double checked and it's the way it should be. `element.readOnly` is the right API

**Pull request merged**
