### PR TITLE
simulate `focus` and `blur` events on click

### PR DESCRIPTION
**Pull request by zemlanin**
also, bump `jsdom` to include a fix for https://github.com/jsdom/jsdom/issues/2499

### CODE REVIEW

**Comment by GabiGrin** [comment]
this is great! been wanting to explore using activeElement to do such hack for jsdom for a while now.
Looks *very* good to me, great tests too.

@shlomitc, can you confirm it also makes sense with WSR usage?

**Comment by shlomitc** [comment]
@mosheKerbel - please talk with Gabi regarding testing strategy to make sure it’s not a breaking change

**Comment by mosheKerbel** [comment]
@GabiGrin  @borisd9 
i would like run the tests of WSR against this new build, is there any option to do it before you merge and release? i mean is there a way to produce a build for this PR?

**Comment by zemlanin** [comment]
_(I've ran `npm run build && npm test && cd adapters/jsdom-react && npm pack` in this branch and gave @mosheKerbel the resulted `.tgz`)_

**Comment by mosheKerbel** [comment]
@zemlanin @GabiGrin @borisd9 
hi guys
we've realised something is of here.
the order of the browser' events is focus and then click
u can see it in this [jsbin](https://jsbin.com/qegahoyeco/edit?html,js,console,output)

but with this change you changed the order of events:
https://github.com/wix-incubator/unidriver/blob/b6a7f01ee296d9885bcc8ffaa9f0541ee06d9dcf/adapters/jsdom-react/src/index.ts#L122

we are now migrating to react16 so errors started to raise.

**Comment by zemlanin** [comment]
@mosheKerbel Have you pushed a branch with react16?

---

[Seems like](https://jsbin.com/larubagiwu/1/edit?html,js,console,output) the correct order is `mousedown -> focus -> mouseup -> click`

**Comment by mosheKerbel** [comment]
> @mosheKerbel Have you pushed a branch with react16?
> 
> [Seems like](https://jsbin.com/larubagiwu/1/edit?html,js,console,output) the correct order is `mousedown -> focus -> mouseup -> click`

if you're looking for reproduction then you can look here
https://github.com/wix/wix-style-react/pull/3863
run only this test `ColorInput.spec.js` 
you will see it fail
then if you change [here](https://github.com/wix/wix-style-react/blob/7c29e1886d4f60e97f3bfe7cf90554736ac7abb4/src/ColorPicker/ColorPickerActions.js#L24) the element to a div by passing the `as="div"` prop
the new code in uniDriver does not handle divs and you will see the test pass

**Comment by zemlanin** [comment]
> run only this test `ColorInput.spec.js`

@mosheKerbel `git clone; cd; npm i; npm run test:unit -- ColorInput` isn't enough to run unit tests:

``` FAIL  src/ColorInput/ColorInput.spec.js
  ● Test suite failed to run

    Cannot find module '../new-icons/system/Close' from 'CloseButton.js'

    However, Jest was able to find:
    	'./InputSuffix.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

    However, Jest was able to find:
    	'./Input.driver.js'
    	'./Input.e2e.js'
    	'./Input.js'
    	'./Input.private.protractor.driver.js'
    	'./Input.protractor.driver.js'
    	'./Input.puppeteer.driver.js'
    	'./Input.scss'
    	'./Input.spec.js'
    	'./Input.uni.driver.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

    However, Jest was able to find:
    	'./ColorInput.e2e.js'
    	'./ColorInput.js'
    	'./ColorInput.private.uni.driver.js'
    	'./ColorInput.spec.js'
    	'./ColorInput.uni.driver.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      2 | import { ButtonNext } from 'wix-ui-core/dist/src/components/button-next';
      3 | import cx from 'classnames';
    > 4 | import Close from '../new-icons/system/Close';
        | ^
      5 | import CloseLarge from '../new-icons/system/CloseLarge';
      6 | import { SIZES } from './constants';
      7 | 

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:230:17)
      at Object.<anonymous> (src/CloseButton/CloseButton.js:4:1)
```

What did I miss? How to "populate" `src/new-icons`?

**Comment by mosheKerbel** [comment]
@zemlanin not sure where did it go but i got a notification where u asked how to set things up.
what i missed in my prev msg was that you need to build the icons first.
you can just ran `npm run storybook`, it will build all things necessary.

**Comment by zemlanin** [comment]
@mosheKerbel I've noticed `CONTRIBUTING.md` right after posting that message, and then deleted it (the message) from here 😅 Thanks

**Pull request merged**
